import type { Task } from '../types';

const now = new Date().toISOString();

export const seedTasks: Task[] = [
  {
    id: 'seed-ai-release-gate',
    title: 'Write LinkedIn post about AI as release gate',
    description:
      'A concise post about using AI to move creative work toward shipping without letting it overrule human taste.',
    station: 'Judgement Hall',
    taskType: 'Post',
    outputFormat: 'Text post',
    audience: 'Social media',
    riskLevel: 'Medium',
    minimumShippableVersion:
      'A 180-250 word post with one concrete example and a clear release principle.',
    confidenceScore: 4,
    releaseDecision: 'Undecided',
    currentBlocker: 'None',
    shipDate: '',
    dueTime: '',
    dueDateFlag: 'Due date not specified in intake.',
    shipGoal: '',
    estimatedTime: '',
    shipTimingNote: 'AZALAI flags that there is no due date yet.',
    outputLink: '',
    createdAt: now,
    updatedAt: now,
    shippedAt: '',
    evidenceNotes: 'Should prove the release-gate concept in public.',
    scopeItems: [],
  },
  {
    id: 'seed-stockroom-card',
    title: 'Create visual mock-up for AZALAI stockroom card',
    description:
      'A tactile inventory-card concept showing task state, scores, and dispatch marks.',
    station: 'Construction',
    taskType: 'Visual',
    outputFormat: 'Image',
    audience: 'Personal',
    riskLevel: 'Low',
    minimumShippableVersion:
      'One card mock-up that proves the stockroom metaphor can feel editorial and usable.',
    confidenceScore: 3,
    releaseDecision: 'Undecided',
    currentBlocker: 'Visual uncertainty',
    shipDate: '',
    dueTime: '',
    dueDateFlag: 'Due date not specified in intake.',
    shipGoal: '',
    estimatedTime: '',
    shipTimingNote: 'AZALAI flags that there is no due date yet.',
    outputLink: '',
    createdAt: now,
    updatedAt: now,
    shippedAt: '',
    evidenceNotes: '',
    scopeItems: [],
  },
  {
    id: 'seed-timbuk2-post',
    title: 'Turn Timbuk2 flood mapping idea into enterprise buyer post',
    description:
      'Convert the flood mapping logistics idea into a buyer-facing post about operational risk and proof.',
    station: 'Clarification Station',
    taskType: 'Strategy',
    outputFormat: 'Text post',
    audience: 'Enterprise buyer',
    riskLevel: 'High',
    minimumShippableVersion:
      'A tight enterprise-facing angle with a clear buyer pain, proof signal, and next question.',
    confidenceScore: 3,
    releaseDecision: 'Undecided',
    currentBlocker: 'Unclear goal',
    shipDate: '',
    dueTime: '',
    dueDateFlag: 'Due date not specified in intake.',
    shipGoal: '',
    estimatedTime: '',
    shipTimingNote: 'AZALAI flags that there is no due date yet.',
    outputLink: '',
    createdAt: now,
    updatedAt: now,
    shippedAt: '',
    evidenceNotes: '',
    scopeItems: [],
  },
];
